1703:2
remoteFailed: [Failure instance: Traceback from remote host -- Traceback (most recent call last):
  File "/home/lsstsw/.local/lib/python2.7/site-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/spread/pb.py", line 891, in _recvMessage
    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
  File "/home/lsstsw/.local/lib/python2.7/site-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/spread/flavors.py", line 114, in remoteMessageReceived
    state = method(*args, **kw)
  File "/home/lsstsw/.local/lib/python2.7/site-packages/buildbot_slave-0.8.8-py2.7.egg/buildslave/bot.py", line 141, in remote_startCommand
    d = self.command.doStart()
  File "/home/lsstsw/.local/lib/python2.7/site-packages/buildbot_slave-0.8.8-py2.7.egg/buildslave/commands/base.py", line 146, in doStart
    d = defer.maybeDeferred(self.start)
--- <exception caught here> ---
  File "/home/lsstsw/.local/lib/python2.7/site-packages/Twisted-14.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/home/lsstsw/.local/lib/python2.7/site-packages/buildbot_slave-0.8.8-py2.7.egg/buildslave/commands/shell.py", line 41, in start
    logEnviron=args.get('logEnviron', True),
  File "/home/lsstsw/.local/lib/python2.7/site-packages/buildbot_slave-0.8.8-py2.7.egg/buildslave/runprocess.py", line 287, in __init__
    os.makedirs(workdir)
  File "/lsst/home/lsstsw/anaconda/lib/python2.7/os.py", line 150, in makedirs
    
  File "/lsst/home/lsstsw/anaconda/lib/python2.7/os.py", line 157, in makedirs
    
exceptions.OSError: [Errno 13] Permission denied: '/lsst/home'
exceptions.OSError: [Errno 13] Permission denied: '/lsst/home'
],